### ISSUE TITLE
Audio API has been dropped in VK

### ISSUE THREAD

**Issue by manuelcortez** [manuelcortez/socializer#10]
In december 2016, VK has announced that third party developers won't have access to generated MP3 links in their audio part of the API. Socializer should get audios by other means, or remove the current audio functions so it will reflect the current state of audio in the application.

**Comment by manuelcortez** [comment]
Audio support has been removed in Socializer for now.

**Comment by beqabeqa473** [comment]
hi.

if you want, you can use my intermediate api with authorization and
most of audio methods.

2018-09-02 17:19 GMT+04:00, Manuel Cortéz <notifications@github.com>:
> Audio support has been removed in Socializer for now.
>
> --
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/manuelcortez/socializer/issues/10#issuecomment-417930416


-- 
with best regards beqa

**Comment by manuelcortez** [comment]
Do you have public documentation regarding it? Have been thinkin in making a parser, though I had no time recently.

**Comment by beqabeqa473** [comment]
no, there are no public documentation.

the only thing you will need to change is after authorization, refresh
token and then make post requests to audio methods, search, get, add,
delete, recommendations, addtoalbum, removefromalbum and so on.

you can look at
https://github.com/beqabeqa473/gozalmusicmini

2018-09-02 22:14 GMT+04:00, Manuel Cortéz <notifications@github.com>:
> Do you have public documentation regarding it? Have been thinkin in making a
> parser, though I had no time recently.
>
> --
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub:
> https://github.com/manuelcortez/socializer/issues/10#issuecomment-417948941


-- 
with best regards beqa
